### ISSUE TITLE
Demo site down?

### ISSUE THREAD

**Issue by machawk1** [mageekguy/jquery.miller.js#5]
The README links to http://mgbx.net/demomiller, which resolves to http://medias.mageekbox.net/miller/demos/miller.html, which is a 404. The entirety of the http://medias.mageekbox.net/ host appears to show the initial setup pages of an nginx instance. Perhaps moving the demo to self-contained github.io/gh-pages hosting would make this more useful and persistent.

**Comment by mageekguy** [comment]
Doh! Thanks for the feedback!
I will fix that ASAP!

**Comment by mageekguy** [comment]
Fixed!
